In [7]:
import numpy as np
import matplotlib.pyplot as plt
import csv

Nb = 50
Nc = 1
#conc = np.array([0.5,2])
conc = np.array([0.05])
box_length = np.array([42.263516])
#box_length = np.array([42.263516,26.624347]) #91.053986 0.005c* single chain
Ncharges = 1
barrier = 3
barrier2 = 3
lambda_d = 10
edot = np.array([0.05714]) 
#edot = np.array([0.00286,0.00571,0.01143,0.05714])
it = 1
ntr = 12
tmax = 25500#last timestep in MSD file
printprops = 1000
dt = 0.0005
Wi = edot*175
nsamp = int(tmax/(dt*printprops))

for c in range(0,len(conc)):
    for i in range(0,len(edot)):
        allMSD = np.array(ntr*[np.array(nsamp*[0.0])]) #stores MSD(t) for each trajectory
        for tr in range(1,ntr+1):


            file_name = "prop/MSD" + str(Nb)+ "_" + str(Nc) + "_" + format(conc[c],'.6f') + "_" +format(box_length[c],'.6f') + "_"+ str(Ncharges) + "_" + format(barrier,'.2f') + "_" + format(barrier2,'.2f')+"_"+ format(lambda_d,'.2f')+"_"+ format(edot[i],'.5f')+"_"+str(tr)+"_" +str(it)+".txt"
            print(file_name)
            
            """
            Extracting data
            """     
            my_data = np.loadtxt(file_name,delimiter=',')
            allMSD[tr-1] = my_data[:nsamp,1] 
        
        MSD = []
        STD = []
        for k in range(0,nsamp):
            x = []
            for j in range(0,ntr):
                x.append(allMSD[j][k])
            #print(np.mean(x))
            MSD.append(np.mean(x))
            STD.append(np.std(x))
        
        if((STD[0]/np.sqrt(ntr)>1) or (str(MSD[0])=='nan')):
            print("Warning - Error is Large or NAN")
        """
        Output
        """     
        
        with open('msd/avgMSD_CA_PSF_'+str(conc[c])+'c_'+str(edot[i])+'_Nchrg'+str(Ncharges)+"_it"+str(it)+".csv",mode='w') as practice_file:
            practice = csv.writer(practice_file,delimiter=',')
            y = ["t","MSD","Err"]
            practice.writerow(y)
            for i in range(0,nsamp):
                x = [(i+1)*printprops*dt,MSD[i],STD[i]/np.sqrt(ntr)]
                practice.writerow(x)
                #print(x)
            
            
print("Done")  
            
            
            
            
            
            
            
            

prop/MSD50_1_0.050000_42.263516_1_3.00_3.00_10.00_0.05714_1_1.txt
prop/MSD50_1_0.050000_42.263516_1_3.00_3.00_10.00_0.05714_2_1.txt
prop/MSD50_1_0.050000_42.263516_1_3.00_3.00_10.00_0.05714_3_1.txt
prop/MSD50_1_0.050000_42.263516_1_3.00_3.00_10.00_0.05714_4_1.txt
prop/MSD50_1_0.050000_42.263516_1_3.00_3.00_10.00_0.05714_5_1.txt
prop/MSD50_1_0.050000_42.263516_1_3.00_3.00_10.00_0.05714_6_1.txt
prop/MSD50_1_0.050000_42.263516_1_3.00_3.00_10.00_0.05714_7_1.txt
prop/MSD50_1_0.050000_42.263516_1_3.00_3.00_10.00_0.05714_8_1.txt
prop/MSD50_1_0.050000_42.263516_1_3.00_3.00_10.00_0.05714_9_1.txt
prop/MSD50_1_0.050000_42.263516_1_3.00_3.00_10.00_0.05714_10_1.txt
prop/MSD50_1_0.050000_42.263516_1_3.00_3.00_10.00_0.05714_11_1.txt
prop/MSD50_1_0.050000_42.263516_1_3.00_3.00_10.00_0.05714_12_1.txt
Done


In [29]:
nsamp = int(tmax/(dt*printprops))

In [8]:
Wi

array([9.9995])

In [49]:
np.array(len(conc)*[np.array(len(it)*np.zeros(tmax))])

array([[0., 0., 0., 0., 0., 0.]])

In [21]:
241%50

41

In [16]:
import numpy as np
pos = [-10.2,-10.2,-5.2]
L = 1
n = np.floor(np.abs(pos)/L)
if(pos.any() > L/2):
    pos -= n*L
elif(pos.any() < -L/2):
    pos += n*L
    
print(pos)

AttributeError: 'list' object has no attribute 'any'

In [33]:
pos = [64.62215594,  41.14395215,  50.03594826]
L = 4.8902868701633055
for i in range(0,len(pos)):
    n = np.floor(np.abs(pos)/L)
    print(n)
    if(pos[i] > L/2):
        for j in range(0,len(n)):
            if(n[j]==0):
                n[j] =1
            
        pos[i] -= n*L
    elif(pos[i] < -L/2):
        for j in range(0,len(n)):
            if(n[j]==0):
                n[j] =1
            
        pos[i] += n*L
  
    print(pos)

[13.  8. 10.]
[array([ 1.04842663, 25.49986098, 15.71928724]), 41.14395215, 50.03594826]


TypeError: only size-1 arrays can be converted to Python scalars

In [34]:
pos = [64.62215594,  41.14395215,  50.03594826]
L = 4.8902868701633055


n = np.floor(np.abs(pos)/L)
    
if(pos[i] > L/2):
    for j in range(0,len(n)):
        if(n[j]==0):
            n[j] =1

    pos[i] -= n*L
elif(pos[i] < -L/2):
    for j in range(0,len(n)):
        if(n[j]==0):
            n[j] =1

    pos[i] += n*L
  
    
print(pos)

[64.62215594, array([-22.42977716,   2.02165719,  -7.75891655]), 50.03594826]


In [32]:
{'L': 1, 'R': array([ 0.6525125 ,  0.75411864,  0.40556725])}

NameError: name 'array' is not defined